language: csharp
mono: none
dotnet: 3.1
script:
  - dotnet restore
  - dotnet build --configuration Release --no-restore
  - dotnet test --no-restore
deploy:
  provider: azure_web_apps
    username: $AZURE_USR
    password: $AZURE_PWD
    site: $AZURE_SITE
    on:
      branch:
        - dev
        - travis
